### ISSUE TITLE
Java Melody does not correctly work with Servlet 2.5

### ISSUE THREAD

**Issue by gosuvigi** [javamelody/javamelody#492]
Inside the MonitoringFilter class, inside the doFilter method the following call:

if (!httpRequest.isAsyncStarted()) 

does not work in Servlet 2.5 since the async feature does not exist, it throws:
java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z

**Comment by evernat** [comment]
True. I almost forgot about Servlet api 2.5 which is quite old now.
In fact, isAsyncStarted was added recently and so javamelody v1.57.0
This is fixed in master and ready for the next release.
A nightly build is available including the fix:
https://javamelody.ci.cloudbees.com/job/javamelody/
