### ISSUE TITLE
MBeans overview does not work with java 1.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#116]
```
MBeans overview does not work with java 1.5.

When you click on Mbeans, then an exception occures: 
java.lang.NoSuchMethodError: 
javax.management.AttributeList.asList()Ljava/util/List;
    at net.bull.javamelody.MBeans.getAttributes(MBeans.java:149)

Reason: This method is available since Java 1.6
Solution: A small change in the code, will resolve the problem. See attached 
patch file.


```

Original issue reported on code.google.com by `eisele.s...@freenet.de` on 20 Jun 2011 at 9:52

Attachments:
- [mbeanJava1-5.patch](https://storage.googleapis.com/google-code-attachments/javamelody/issue-116/comment-0/mbeanJava1-5.patch)
