### ISSUE TITLE
Ehcache 2.7.0 doesn't work with javamelody 1.43.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#293]
```
What steps will reproduce the problem?
1. java j2ee project(no Spring and Hibernate)
2. This web container includes Ehcache(2.7.0) & javamelody 1.43.0 libraries.
3. when I call the Ehcache get cache method, the javamelody throws the 
exception information below.


What is the expected output? What do you see instead?
can normally use javamelody.

What version of the product are you using? On what application server, JDK,
operating system? Windows 7
App Server: Tomcat
javamelody version: 1.43.0

Please provide any additional information below.

SEVERE: Servlet.service() for servlet [default] in context with path 
[/myProject] threw exception [Filter execution threw an exception] with root 
cause
java.lang.NoSuchMethodError: 
net.sf.ehcache.Ehcache.getStatistics()Lnet/sf/ehcache/Statistics;
    at net.bull.javamelody.CacheInformations.<init>(CacheInformations.java:59)
    at net.bull.javamelody.CacheInformations.buildCacheInformationsList(CacheInformations.java:165)
    at net.bull.javamelody.JavaInformations.<init>(JavaInformations.java:188)
    at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:136)
    at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:340)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:170)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.zyxel.template.model.filters.ActionHandler.doFilter(ActionHandler.java:43)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:581)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at com.jamonapi.http.JAMonTomcatValve.invoke(JAMonTomcatValve.java:72)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

```

Original issue reported on code.google.com by `enzo...@gmail.com` on 15 Mar 2013 at 2:39
