### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/servlet/AsyncContext

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#230]
```
What steps will reproduce the problem?
After upgrading from Java Melody 1.33 to 1.38 a JSTL call to 
${pageContext.request.localName} on our website now throws 

java.lang.NoClassDefFoundError: javax/servlet/AsyncContext
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethods(Unknown Source)
    at java.beans.Introspector$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.beans.Introspector.getPublicDeclaredMethods(Unknown Source)
    at java.beans.Introspector.getTargetMethodInfo(Unknown Source)
    at java.beans.Introspector.getBeanInfo(Unknown Source)
    at java.beans.Introspector.getBeanInfo(Unknown Source)
    at org.apache.commons.el.BeanInfoManager.initialize(BeanInfoManager.java:226)
    at org.apache.commons.el.BeanInfoManager.checkInitialized(BeanInfoManager.java:210)
    at org.apache.commons.el.BeanInfoManager.getProperty(BeanInfoManager.java:295)
    at org.apache.commons.el.BeanInfoManager.getBeanInfoProperty(BeanInfoManager.java:179)
    at org.apache.commons.el.ArraySuffix.evaluate(ArraySuffix.java:308)
    at org.apache.commons.el.ComplexValue.evaluate(ComplexValue.java:145)
    at org.apache.commons.el.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:263)
    at org.apache.commons.el.ExpressionEvaluatorImpl.evaluate(ExpressionEvaluatorImpl.java:190)
    at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:924)
    at org.apache.jsp.tag.web.pageComponents.serverInfo_tag.doTag(serverInfo_tag.java:111)

What is the expected output? What do you see instead?
Page does not render.


What version of the product are you using? On what application server, JDK,
operating system?
Apache Tomcat/5.5.33, Windows 7


Please provide any additional information below.
Reverting to Javamelody 1.33 solves the issue

```

Original issue reported on code.google.com by `jeffsou...@gmail.com` on 19 Jun 2012 at 7:48
