### ISSUE TITLE
Ehcache problem with 1.64.0

### ISSUE THREAD

**Issue by pethers** [javamelody/javamelody#616]
Using ehache 2.10.3, the behavior of "isEhcache27();" has changed, worked well with 1.63.0.

`
java.lang.NoSuchMethodError: net.sf.ehcache.Ehcache.getStatistics()Lnet/sf/ehcache/Statistics;
	at net.bull.javamelody.CacheInformations.<init>(CacheInformations.java:82)
	at net.bull.javamelody.CacheInformations.buildCacheInformationsList(CacheInformations.java:168)
	at net.bull.javamelody.JavaInformations.<init>(JavaInformations.java:181)
	at net.bull.javamelody.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:165)
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:370)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:188)
`

Since it is not detected as >= 2.7 the line "final Statistics statistics = cache.getStatistics();" throws exception.

**Comment by evernat** [comment]
many thanks, it's fixed now (f776397).
I will release 1.65.0.

**Comment by pethers** [comment]
Thanks yourself, 1.65.0 release works well :)
