### ISSUE TITLE
After upgrade: NoClassDefFoundError org.jboss.weld.xml.BeansXmlHandler

### ISSUE THREAD

**Issue by samuelfac** [javamelody/javamelody#635]
Error on initialize my war, after I upgrade **from 1.65.0 to 1.66.0 or 1.67.0**.

I try to put the package **org.jboss.weld.core** (where the class is in), but the same error occurs.

LOG:

_14:32:57,928 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC00001: Failed to start service jboss.deployment.unit."portal.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."portal.war".PARSE: Failed to process phase PARSE of deployment "portal.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:119) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_60]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_60]
**Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jboss.weld.xml.BeansXmlHandler**
	at org.jboss.as.weld.deployment.BeansXmlParser.parse(BeansXmlParser.java:83)
	at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.parseBeansXml(BeansXmlProcessor.java:133)
	at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.deploy(BeansXmlProcessor.java:84)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
	... 5 more_

**Comment by evernat** [comment]
There is an issue #634 which is already fixed in master.
Can you try the new build javamelody-core-1.68.0-SNAPSHOT.jar from
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/
Thanks.

**Comment by samuelfac** [comment]
When I put new jar, occurred another error:


_09:57:01,516 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-7) MSC00001: Failed to start service jboss.deployment.unit."portal.war".PARSE: org.jboss.msc.service.StartException in service jboss.deployment.unit."portal.war".PARSE: Failed to process phase PARSE of deployment "portal.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:119) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
**Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.jboss.weld.logging.WeldMessageConveyor**
	at org.jboss.weld.logging.WeldMessageConveyor.<init>(WeldMessageConveyor.java:61)
	at org.jboss.weld.logging.WeldMessageConveyerFactory.getDefaultMessageConveyer(WeldMessageConveyerFactory.java:27)
	at org.jboss.weld.logging.LoggerFactory.<init>(LoggerFactory.java:37)
	at org.jboss.weld.logging.LoggerFactory.loggerFactory(LoggerFactory.java:51)
	at org.jboss.weld.xml.BeansXmlHandler.<clinit>(BeansXmlHandler.java:45)
	at org.jboss.as.weld.deployment.BeansXmlParser.parse(BeansXmlParser.java:83)
	at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.parseBeansXml(BeansXmlProcessor.java:133)
	at org.jboss.as.weld.deployment.processors.BeansXmlProcessor.deploy(BeansXmlProcessor.java:84)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) **[jboss-as-server-7.1.1.Final.jar:7.1.1.Final]**
	... 5 more_

**Comment by evernat** [comment]
This seems to be a bug in Weld vs Guava version. You can ask to Google with "IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class org.jboss.weld.logging.WeldMessageConveyor").
See for example:
https://issues.jboss.org/browse/RF-13725

In fact, Weld is using MapMaker.makeComputingMap:
http://grepcode.com/file/repo1.maven.org/maven2/org.jboss.weld/weld-core/2.0.0.SP1/org/jboss/weld/logging/WeldMessageConveyor.java/#61
But the MapMaker.makeComputingMap method was deprecated and is no longer public since Guava 15:
http://grepcode.com/file/repo1.maven.org/maven2/com.google.guava/guava/15.0/com/google/common/collect/MapMaker.java#581

If you use Guava in your app, I suggest to downgrade Guava to v14 or v13, or to Upgrade Weld / JBoss.

**Comment by samuelfac** [comment]
Yep. I have guava v18.

Tks for return.
